sudo: required
services:
    - docker

before_install:
    - docker build -t simonszdenver/docker-react -f Dockerfile.dev .

# script:
#     - docker run simonszdenver/docker-react npm run test -- --coverage


deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-874513772624"
    bucket_path: "docker-react"
    on:
        branch: master

        
