sudo: required
services:
    - docker

before_install:
    - docker build -t simonszdenver/docker-react -f Dockerfile.dev .

script:
    - docker run simonszdenver/docker-react npm run test -- --coverage